global: &global
  # название сайта
  site_title: Feedback

  
development: &development
  <<: &global
  host: 127.0.0.1
  port: 3000


test:
  <<: *development
  permissions_verification_enabled: false


production: &production
  <<: *development
