global: &global
  # название сайта
  site_title: "Сервис фидбека"
  app_name: "Сервис фидбека"
  status:
    1: "Новое"
    2: "В обработке" 
    3: "Обработано"
  label:
    1: "label-success"
    2: "label-info"
    3: "label-default"
  button:
    1: "btn-success"
    2: "btn-info"
    3: "btn-default"
  per_page: 20

  
development: &development
  <<: *global
  host: "http://feedback-test-app.herokuapp.com"
  port: 80


test:
  <<: *development
  permissions_verification_enabled: false


production: &production
  <<: *development
  port: 80
